version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: library-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - DATABASE_PATH=/app/data/data.db
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost:${FRONTEND_PORT:-3001}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - backend_data:/app/data
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - database-init

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: library-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-3000}
    ports:
      - "${FRONTEND_PORT:-3001}:80"
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      backend:
        condition: service_healthy

  database-init:
    image: alpine:latest
    container_name: library-db-init
    volumes:
      - backend_data:/data
    command: >
      sh -c "
        if [ ! -f /data/data.db ]; then
          echo 'Initializing database directory...';
          touch /data/data.db;
          chmod 664 /data/data.db;
          echo 'Database file created successfully';
        else
          echo 'Database already exists';
        fi
      "
    networks:
      - library-network

volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}

networks:
  library-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16